=== SheepGuru/aerodrome-for-jet/src/main/resources/jetimport.conf.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/jetimport.conf.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE config SYSTEM "jetimport.conf.dtd">

    <config>
    ...
    </config>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT config (log|client|jet)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT log (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT client (readTimeout|accept|acceptLanguage|allowUntrustedSSL)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT readTimeout (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT accept (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT acceptLanguage (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT allowUntrustedSSL (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT jet (host|username|password|merchantId|uri)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT host (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT username (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT password (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT merchantId (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT uri (token|authTest|products)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT token (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT authTest (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT products (get|put|delete)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT get (sku|price)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sku (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT price (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT put (sku|image|price|inventory|shipException)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT image (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT inventory (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT shipException (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT delete EMPTY>

=== SheepGuru/aerodrome-for-jet/src/main/resources/jetimport.conf.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE config SYSTEM "jetimport.conf.dtd">


<!--
Configuration Settings for the JetImport Application


Variable Placeholders
=====================
{sku} - The product SKU
-->

<config>

  <!-- Log file name -->
  <log>jetimport.log</log>

  <!-- HTTP Client Configuration -->
  <client>
    <!-- Socket read timeout in milliseconds -->
    <readTimeout>10000</readTimeout>

    <!-- Accept Header Value -->
    <!-- text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 -->
    <accept>
      <![CDATA[
      application/json,text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
      ]]>
    </accept>

    <!-- Accept-Language Header Value -->
    <acceptLanguage>
      <![CDATA[
      en-US,en;q=0.5
      ]]>
    </acceptLanguage>

    <!-- Toggle self-signed certificate rejection -->
    <allowUntrustedSSL>true</allowUntrustedSSL>
  </client>

  <!-- Jet.com API Configuration -->
  <!-- Currently, your authentication details reside here: -->
  <!-- https://partner.jet.com/dashboard/start -->
  <jet>
    <!-- The Hostname for the Jet API (no trailing slash) -->
    <host>https://merchant-api.jet.com</host>

    <!-- Your Jet API Username -->
    <username></username>

    <!-- Your Jet API Password -->
    <password></password>

    <!-- Jet API Merchant Id -->
    <merchantId></merchantId>

    <!-- Jet API Endpoint URI's -->
    <uri>
      <!-- Retrieve authentication token -->
      <!-- https://developer.jet.com/security -->
      <token>/api/Token</token>

      <!-- Authentication testing endpoint -->
      <!--
       Jet API provides the test endpoint to be used just for the checking
       of Security arrangement, that is, /api/authcheck. Upon obtaining a
       valid bearer token, the Jet API user may access this endpoint and,
       given the expected response has been obtained, the user may start
       using other Jet API functions that require authorization.
      -->
      <authTest>/api/authcheck</authTest>

      <!-- Product-related endpoints -->
      <!-- https://developer.jet.com/docs/services/5565ca949a274a12b0b3a2a3/operations/5565d4be9a274a12b0b3a2ae -->
      <products>
        <!-- Get Commands -->
        <get>
          <!-- Get a SKU/Product -->
          <sku>/api/merchant-skus/{sku}</sku>

          <!-- Get some price data -->
          <price>/api/merchant-skus/{sku}/price</price>
        </get>

        <!-- Put commands -->
        <put>
          <!-- Add a new SKU/Product -->
          <sku>/api/merchant-skus/{sku}</sku>

          <!-- Add image url's to the product -->
          <image>/api/merchant-skus/{sku}/image</image>

          <!-- Add some price data -->
          <price>/api/merchant-skus/{sku}/price</price>

          <!-- Add inventory to the product -->
          <inventory>/api/merchant-skus/{sku}/inventory</inventory>

          <!-- Add shipping exceptions -->
          <shipException>/api/merchant-skus/{sku}/shippingexception</shipException>
        </put>

        <!-- Delete Commands -->
        <delete>

        </delete>
      </products>
    </uri>
  </jet>
</config>
